// Code generated by rpc-gen. DO NOT EDIT.
package impl

import (
	"git.pinquest.cn/base/log"
	"git.pinquest.cn/qlb/brick/redisgroup"
	"git.pinquest.cn/qlb/envconfig"
)

type StateRedis struct {
	RedisGroup *redisgroup.RedisGroup
}
type StateRedisConf struct {
	RedisSvrAutoGen string `validate:"required"`
}

func InitStateRedis() error {
	envCfg, err := envconfig.LoadConfig()
	if err != nil {
		log.Error(err)
		return err
	}
	S.RedisGroup, err = redisgroup.New(S.Conf.RedisSvrAutoGen, envCfg.RedisPassword)
	if err != nil {
		log.Errorf("connect redis %S err %S", S.Conf.RedisSvrAutoGen, err)
		return err
	}
	return nil
}
