// Code generated by rpc-gen. DO NOT EDIT.
package impl

import "git.pinquest.cn/qlb/brick/freq"

var freqRules = []*freq.Rule{}

func RegisterFreqRules() error {
	return freq.RegisterRules(freqRules)
}
