// Code generated by rpc-gen. DO NOT EDIT.
package main

import (
	"git.pinquest.cn/base/aiadmin"
	"git.pinquest.cn/base/aiadminserver/impl"
	"git.pinquest.cn/qlb/brick/rpc"
)

var CmdMap = []rpc.ServerCmdMap{
	{Path: aiadmin.CreateDatasetCMDPath, Handler: impl.CreateDataset, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.UpdateDatasetCMDPath, Handler: impl.UpdateDataset, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetDatasetListCMDPath, Handler: impl.GetDatasetList, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.DeleteDatasetCMDPath, Handler: impl.DeleteDataset, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.CheckDatasetUsageCMDPath, Handler: impl.CheckDatasetUsage, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.FAQImportExcelCMDPath, Handler: impl.FAQImportExcel, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.CheckFAQFileFormatTaskCMDPath, Handler: impl.CheckFAQFileFormatTask, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.AddFAQCMDPath, Handler: impl.AddFAQ, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.DeleteFAQCMDPath, Handler: impl.DeleteFAQ, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.UpdateFAQCMDPath, Handler: impl.UpdateFAQ, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetFAQListCMDPath, Handler: impl.GetFAQList, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.AddFAQCategoryCMDPath, Handler: impl.AddFAQCategory, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetFAQCategoryListCMDPath, Handler: impl.GetFAQCategoryList, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.DeleteFAQCategoryCMDPath, Handler: impl.DeleteFAQCategory, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.UpdateFAQCategoryCMDPath, Handler: impl.UpdateFAQCategory, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.CreateWorkflowCMDPath, Handler: impl.CreateWorkflow, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetWorkflowListCMDPath, Handler: impl.GetWorkflowList, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetWorkflowDetailCMDPath, Handler: impl.GetWorkflowDetail, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.UpdateWorkflowCMDPath, Handler: impl.UpdateWorkflow, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.DeleteWorkflowCMDPath, Handler: impl.DeleteWorkflow, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.ToggleWorkflowStatusCMDPath, Handler: impl.ToggleWorkflowStatus, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.TestWorkflowCMDPath, Handler: impl.TestWorkflow, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetWorkflowNodeTypesCMDPath, Handler: impl.GetWorkflowNodeTypes, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetPromptTemplatesCMDPath, Handler: impl.GetPromptTemplates, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetWorkflowDatasetsCMDPath, Handler: impl.GetWorkflowDatasets, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetLLMModelsCMDPath, Handler: impl.GetLLMModels, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.HandleAIWorkflowTaskCMDPath, Handler: impl.HandleAIWorkflowTask, CmdID: 0, Flags: 0, UserType: "sys", PermList: nil, Options: map[string]string{"UserType": "sys"}},
	{Path: aiadmin.HandleAIWorkflowBufferEventCMDPath, Handler: impl.HandleAIWorkflowBufferEvent, CmdID: 0, Flags: 0, UserType: "sys", PermList: nil, Options: map[string]string{"UserType": "sys"}},
	{Path: aiadmin.GetRobotActiveWorkflowConfigCMDPath, Handler: impl.GetRobotActiveWorkflowConfig, CmdID: 0, Flags: 0, UserType: "sys", PermList: nil, Options: map[string]string{"UserType": "sys"}},
	{Path: aiadmin.GetWorkflowRunListCMDPath, Handler: impl.GetWorkflowRunList, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
	{Path: aiadmin.GetWorkflowRunDetailCMDPath, Handler: impl.GetWorkflowRunDetail, CmdID: 0, Flags: 0, UserType: "", PermList: nil, Options: nil},
}
